# Generated by Django 4.0.3 on 2022-03-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=58, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is_active')),
                ('is_public', models.BooleanField(blank=True, default=True, verbose_name='is_public')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'permissions': [('owner', 'Owner'), ('admin', 'Admin'), ('participant', 'Participant')],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='How much does the item cost?', max_digits=20, null=True, verbose_name='Value')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Weight in g', max_digits=20, null=True, verbose_name='Weight')),
                ('description', models.TextField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('is_public', models.BooleanField(blank=True, default=True, verbose_name='is_public')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is_active')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='list.list', verbose_name='list')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
