# Generated by Django 4.0.4 on 2022-05-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=255, verbose_name='Description'),
        ),
    ]
